# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker build -t my-python-app .
  displayName: 'Build Docker image'

- script: |
    docker run my-python-app python math_ops.py
  displayName: 'Run Python script'

- script: |
     python -m venv env
     source env/bin/activate
     /usr/bin/python -m pip install --upgrade pip
     /usr/bin/python -m pip install -r requirements.txt
     /usr/bin/python -m pip install pytest coverage
  displayName: 'Install dependencies'

- script: |
    python -m coverage run --source=. -m pytest test_math_ops.py
    python -m coverage report -m
  displayName: 'Run unit tests with coverage'