# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Container registry information
  containerRegistry: 'MyContainer23Registry'
  containerRepository: 'SW_Assignment1'
  containerTag: '$(Build.BuildId)'
  containerImageName: '$(containerRegistry)/$(containerRepository):$(containerTag)'
  # ACI information
  aciResourceGroup: 'MyResourceGroup'
  aciName: 'mycontainerinstance'
  aciRegion: 'West US'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '$(containerRegistry)'
    repository: '$(containerRepository)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(containerTag)
      latest
  displayName: 'Build Docker image'

- task: Docker@2
  inputs:
    containerRegistry: '$(containerRegistry)'
    repository: '$(containerRepository)'
    command: 'push'
    tags: |
      $(containerTag)
      latest
  displayName: 'Push Docker image'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'My Azure Subscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az container start --resource-group $(aciResourceGroup) --name $(aciName)
  displayName: 'Start Azure Container Instance'