# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory to /SW_Assignment1
WORKDIR /SW_Assignment1

# Copy the requirements file into the container
COPY requirements.txt .

# Install any dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY myscript.py .
COPY test_myscript.py .

# Set the command to run the unit tests
CMD [ "pytest" ,  "test_myscript.py"]